# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 겾두의 잡동사니
email: tkddbs2468@naver.com
description: >- # this means to ignore newlines until "baseurl:"
  겾두의 잡 생각들이 모이는 공간입니다.
baseurl: "/blog/" # the subpath of your site, e.g. /blog
url: "https://tkddbs2468.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  tkddbs2468
domain: tkddbs2468.github.io 

# Build settings
theme: minima
plugins:
  - jekyll-remote-theme

#not-pure-poole theme
remote_theme: vszhub/not-pure-poole

#avatar,bg
avatar: /avatar.jpg
cover_image: /bg.jpg

#author
author:
  name: Sangyoon Lee
  url: https://github.com/tkddbs2468/
  email: tkddbs2468@naver.com

#blog app info
#github-pages
#client_id: 9092637f9c95883e7fa2
#client_secret: b4873a95f775e2730e15cb2e0c9c5d8d92df3b43 
#localhost
client_id: 2c42bf5d57bfab58f14c
client_secret: ad9da06bf1cc28006e5e6a9f5f8a48806410cf0a

#personal access token
token: Z2hwX04zSnlGTTV3Y0dnNVhBWGRTNndQTHV0TTBETEwyUjJLeWZGZg==

# set timezone
timezone: Asia/Seoul

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
